name: Python package build and publish

on:
  push:
    # branches: [ $default-branch ]
    branches: [ githubbuilds ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2
      uses: actions/setup-python@v2
      with:
        python-version: 2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install setuptools fabric pycrypto ecdsa
        if [ -f build-requirements.txt ]; then pip install -r build-requirements.txt; fi
    - name: Build package
      run: |
        python setup.py -q sdist --dist-dir 'dist/'
    - name: List contents of dist/
      run: |
        ls -al 'dist/'
